### PR TITLE
Fix for issue #67 - ImmutableSetMultimap ordering

### PR DESCRIPTION
**Pull request by michaelhixson**
https://github.com/FasterXML/jackson-datatype-guava/issues/67

### CODE REVIEW

**Comment by michaelhixson** [comment]
Not sure what's up with the Travis build failure.  Is master the wrong branch to be using?

**Comment by cowtowncoder** [comment]
No, `master` is the right branch. Not sure where the failure came, will have a look. Almost certainly from 2.6.0 databind.

**Comment by cowtowncoder** [comment]
Turns out it was a combination of a missing override, minor change in checking logic. Build should pass again.

**Comment by cowwoc** [comment]
Time to revisit this pull request?

**Pull request merged**
